#!/bin/bash
# eh_merge_folder 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {
    dx mkdir -p "${project}:/$output_folder/tmp"
    
    dx download "$input_vcf" -o "all_chrs_EH.vcf.gz"
    dx download "$input_vcf_index" -o "all_chrs_EH.vcf.gz.csi"
    dx download "$multi_str_ids" -o "multi_str_ids.txt"
    dx download "$samples_to_remove" -o "samples_to_remove.txt"
    input_vcf_id=$(echo "$input_vcf" | jq -r '."$dnanexus_link"')
    input_vcf_index_id=$(echo "$input_vcf_index" | jq -r '."$dnanexus_link"')


    for chr in "${chr_array[@]}"; do
        echo "processing ${chr}"
        
    # Submit the job to DNAnexus
        job_id=$(dx run  --priority high -y "MS STR study:/str_qc_eh" -ichr=${chr} \
            -iinput_vcf=$input_vcf_id -iinput_vcf_index=$input_vcf_index_id \
            -ioutput_prefix=$output_prefix -iAAP_threshold=$AAP_threshold \
            -iNTSR_threshold=$NTSR_threshold -iNLC_threshold=$NLC_threshold \
            -iMADSP_threshold=$MADSP_threshold \
            -ivariant_missing_threshold=$variant_missing_threshold \
            -ihomozygosity_threshold=$homozygosity_threshold \
            -iADSP_comparison_threshold=$ADSP_comparison_threshold \
            -ioutput_folder=$output_folder -iproject="${project}" \
            --instance-type="mem3_ssd2_v2_x2" \
            --destination=$output_folder \
            --yes --brief \
            --detach)
    
    # Append the job ID to the array
        job_ids+=("$job_id")
    done 
    filepath="all_chrs_EH.vcf.gz"
    bash GAAP.sh $filepath $GAAP_threshold
    
    if [ ${#job_ids[@]} -gt 0 ]; then
        echo "Waiting for jobs: ${job_ids[@]}"
        dx wait "${job_ids[@]}"
    else
        echo "No new jobs were submitted since all expected files already exist in $DESTINATION_FOLDER."
    fi
    
    for chr in "${chr_array[@]}"; do
    full_address=${project}:/${output_folder}/tmp/${chr}_final.vcf.gz
    dx download "$full_address"
    full_address=${project}:/${output_folder}/tmp/${chr}_final.vcf.gz.csi
    dx download "$full_address"
    full_address=${project}:/${output_folder}/tmp/${chr}_all_qc.tsv
    dx download "$full_address"
    done
    
    #make list of samples to exclude
    cat samples_to_remove.txt low_GAAP.txt > GAAP_plus_snp_samples_to_remove.txt
    
    #make a list of variants to exclude
    > all_chrs_all_qc.tsv
    for chr in "${chr_array[@]}"; do
        tail -n +2 "${chr}_all_qc.tsv" >> all_chrs_all_qc.tsv
    done
    
    # Extract the first field from the combined file
    cut -f1 all_chrs_all_qc.tsv > variants_to_exclude.txt
    awk '{print $1, "multistr"}' >> variants_to_exclude.txt

    
    #concat vcfs
    # An array to hold the names of filtered files
    filtered_files=()

    # Loop over each chromosome
    for chr in "${chr_array[@]}"; do
        input="${chr}_final.vcf.gz"
        output="${chr}_final.filtered.vcf.gz"
    
        # Filter the VCF: 
        # --samples-file ^GAAP_plus_snp_samples_to_remove.txt excludes samples listed in the file 
        bcftools view \
            --samples-file ^GAAP_plus_snp_samples_to_remove.txt \
            --force-samples \
            "$input" \
            -O z -o "$output"
        bcftools index "$output"
        # Add the output filename to the array
        filtered_files+=("$output")
    done
    
    # Concatenate the filtered VCF files into one final VCF
    bcftools concat -a -O z -o all_chrs_final.filtered.vcf.gz "${filtered_files[@]}"
    bcftools index all_chrs_final.filtered.vcf.gz
    #remove vars
    bcftools query -f '%CHROM\t%POS\t%INFO/VARID\n' all_chrs_final.filtered.vcf.gz > variant_key.txt
    # Filter keys that match the VARIDs in exclude_varids.txt
    awk 'FNR==NR {ex[$1]; next} ($3 in ex)' variants_to_exclude.txt variant_key.txt > filtered_keys.txt
    head filtered_keys.txt
    awk '{print $1"\t"$2-1"\t"$2}' filtered_keys.txt > exclusion_regions.bed
    head exclusion_regions.bed
    bcftools view -T '^exclusion_regions.bed' --threads 4 -Oz -o vars_filtered.vcf.gz all_chrs_final.filtered.vcf.gz
    
    
    #remove missing_samples
    bcftools query -f '[%SAMPLE\t%GT\n]' vars_filtered.vcf.gz | awk ' { total[$1]++; if ($2 == "./.") missing[$1]++; } END { for (sample in total) { printf("%s\t%.5f\n", sample, missing[sample]/total[sample]); } }'> sample_missingness.txt
    awk -v threshold="$sample_missing_threshold" '$2 > threshold {print $1}' sample_missingness.txt > high_missingness_samples.txt
    bcftools view -S ^high_missingness_samples.txt --threads 4 -o final_QC.vcf.gz -Oz vars_filtered.vcf.gz
    bcftools index final_QC.vcf.gz
    awk '{print $1, "snp_qc"}' samples_to_remove.txt  > all_samples_to_remove.txt
    awk '{print $1, "low_GAAP"}' low_GAAP.txt >> all_samples_to_remove.txt
    awk '{print $1, "missingness"}' high_missingness_samples.txt >> all_samples_to_remove.txt


    output_vcf=$(dx upload final_QC.vcf.gz --brief --path "MS STR study:/$output_folder/${output_prefix}_final_QC.vcf.gz" -p)
    output_vcf_index=$(dx upload final_QC.vcf.gz.csi --brief --path "MS STR study:/$output_folder/${output_prefix}_final_QC.vcf.gz.csi" -p)
    QC_info_vars=$(dx upload variants_to_exclude.txt --brief --path "MS STR study:/$output_folder/${output_prefix}_variants_to_exclude.txt" -p)
    QC_info_samples=$(dx upload all_samples_to_remove.txt --brief --path "MS STR study:/$output_folder/${output_prefix}_samples_to_remove.txt" -p)
    
    dx-jobutil-add-output output_vcf "$output_vcf" --class=file
    dx-jobutil-add-output output_vcf_index "$output_vcf_index" --class=file
    dx-jobutil-add-output QC_info_vars "$QC_info_vars" --class=file
    dx-jobutil-add-output QC_info_samples "$QC_info_samples" --class=file
    
}
