#!/bin/bash
# eh_merge_folder 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {
    dx mkdir -p "MS STR study:/${output_folder}"
    dx download "$input_vcf" -o "all_chrs_EH.vcf.gz"
    dx download "$input_vcf_index" -o "all_chrs_EH.vcf.gz.csi"
    # Create a working directory
    work_dir="${output_prefix}_work"
    mkdir -p "${work_dir}"
    QC_dir="${work_dir}/QC"
    mkdir -p "${QC_dir}"
    # Function to process each chromosome
    echo "Processing chromosome ${chr}"
    mkdir -p "${work_dir}/${chr}"

        # Extract and filter chromosome
    bcftools view -r ${chr} all_chrs_EH.vcf.gz --threads 2 -Oz -o "${work_dir}/${chr}/${chr}.vcf.gz"
    bcftools index "${work_dir}/${chr}/${chr}.vcf.gz"
        # Apply filter for AAP
    bcftools +setGT "${work_dir}/${chr}/${chr}.vcf.gz" -- -t q -n . -i "FORMAT/AAP<${AAP_threshold}" > "${work_dir}/${chr}/${chr}_temp1.vcf"
    bgzip -f "${work_dir}/${chr}/${chr}_temp1.vcf" > "${work_dir}/${chr}/${chr}_temp1.vcf.gz"
    bcftools index "${work_dir}/${chr}/${chr}_temp1.vcf.gz"
    rm "${work_dir}/${chr}/${chr}.vcf.gz"
        # Apply filter for NTSR
    bcftools +setGT "${work_dir}/${chr}/${chr}_temp1.vcf.gz" -- -t q -n . -i "FORMAT/NTSR>${NTSR_threshold}" > "${work_dir}/${chr}/${chr}_temp2.vcf"
    bgzip -f "${work_dir}/${chr}/${chr}_temp2.vcf" > "${work_dir}/${chr}/${chr}_temp2.vcf.gz"
    bcftools index "${work_dir}/${chr}/${chr}_temp2.vcf.gz"
    rm "${work_dir}/${chr}/${chr}_temp1.vcf.gz"
        # Apply filter for NLC
    bcftools +setGT "${work_dir}/${chr}/${chr}_temp2.vcf.gz" -- -t q -n . -i "FORMAT/NLC<${NLC_threshold}" > "${work_dir}/${chr}/${chr}_temp3.vcf"
    bgzip -f "${work_dir}/${chr}/${chr}_temp3.vcf" > "${work_dir}/${chr}/${chr}_temp3.vcf.gz"
    bcftools index "${work_dir}/${chr}/${chr}_temp3.vcf.gz"
    rm "${work_dir}/${chr}/${chr}_temp2.vcf.gz"
        # Apply filter for MADSP
    bcftools +setGT "${work_dir}/${chr}/${chr}_temp3.vcf.gz" -- -t q -n . -i "FORMAT/MADSP<${MADSP_threshold}" > "${work_dir}/${chr}/${chr}_final.vcf"
    bgzip -f "${work_dir}/${chr}/${chr}_final.vcf" > "${work_dir}/${chr}/${chr}_final.vcf.gz"
    bcftools index "${work_dir}/${chr}/${chr}_final.vcf.gz"
    rm "${work_dir}/${chr}/${chr}_temp3.vcf.gz"


     # Calculate variant missingness for the chromosome
    bcftools query -f '%CHROM\t%POS\t%VARID\t[%GT\t]\n' "${work_dir}/${chr}/${chr}_final.vcf.gz" | \
    awk 'BEGIN { FS="\t"; OFS="\t" }
         {
           total=0; missing=0;
           for (i=4; i<=NF; i++) {
             total++;
             if ($i == "./.") missing++;
           }
           print $1, $2, $3, missing/total;
         }' | awk -v threshold=${variant_missing_threshold} -v OFS='\t' '$4 > threshold {print $1, $2, $3}' > "${QC_dir}/${chr}_high_miss_variants.txt"

    bcftools query -f '%VARID[\t%GT\t%ADSP]\n' ${work_dir}/${chr}/${chr}_final.vcf.gz > ${QC_dir}/gt_adsp.tsv
    
    
    
    Rscript extraQC.R ${work_dir}/${chr}/${chr}_final.vcf.gz $homozygosity_threshold $ADSP_comparison_threshold $work_dir ${QC_dir}/gt_adsp.tsv $chr
    
    
    dx mkdir -p "MS STR study:/${output_folder}/tmp"
    chr_output_vcf=$(dx upload ${work_dir}/${chr}/${chr}_final.vcf.gz --brief --path "MS STR study:/${output_folder}/tmp/" -p)
    chr_output_vcf_index=$(dx upload ${work_dir}/${chr}/${chr}_final.vcf.gz.csi --brief --path "MS STR study:/${output_folder}/tmp/" -p)
    chr_QC_info=$(dx upload "all_qc.tsv" --brief --path "MS STR study:/${output_folder}/tmp/${chr}_all_qc.tsv" -p)
    hi_miss_vars=$(dx upload ${QC_dir}/${chr}_high_miss_variants.txt --brief --path "MS STR study:/${output_folder}/tmp/" -p)
    homozygosity_fails=$(dx upload "failed_homozygosity.tsv" --brief --path "MS STR study:/${output_folder}/tmp/${chr}_failed_homozygosity.tsv" -p)
    adsp_fails=$(dx upload "failed_adsp.tsv" --brief --path "MS STR study:/${output_folder}/tmp/${chr}_failed_adsp.tsv" -p)
    
    dx-jobutil-add-output chr_output_vcf "$chr_output_vcf" --class=file
    dx-jobutil-add-output chr_output_vcf_index "$chr_output_vcf_index" --class=file
    dx-jobutil-add-output chr_QC_info "$chr_QC_info" --class=file
    dx-jobutil-add-output hi_miss_vars "$hi_miss_vars" --class=file
    dx-jobutil-add-output homozygosity_fails "$homozygosity_fails" --class=file
    dx-jobutil-add-output adsp_fails "$adsp_fails" --class=file
    
    

    
        
   
    

    
}
